package br.com.matheuscrivellaro.api_estoque_veiculos.dto.estoqueXml;

import jakarta.xml.bind.annotation.XmlRootElement;
import lombok.Data;

import java.util.List;

@Data
@XmlRootElement(name = "Veiculo")
public class Veiculo {
    private String codigoCliente;
    private String codigoVeiculo;
    private String usadoNovo;
    private String tipoVeiculo;
    private String categoria;
    private String marca;
    private String modelo;
    private String versao;
    private String procedencia;
    private String cilindrada;
    private String potencia;
    private String tipoMotor;
    private String freio;
    private String refrigeracao;
    private String anoModelo;
    private String anoFabricacao;
    private String combustivel;
    private String transmissao;
    private String codigoFIPE;
    private String cor;
    private String segundaCor;
    private double preco;
    private String precoPromocional;
    private String alienado;
    private String comDivida;
    private String valorParcelaDivida;
    private String numeroParcelasDivida;
    private String valorTotalDivida;
    private String placa;
    private String cidade;
    private int kilometragem;
    private String qtdDonos;
    private int qtdPortas;
    private String aceitaPermutaCarro;
    private String aceitaPermutaOutroBem;
    private String valorPermutaCarro;
    private String valorPermutaOutroBem;
    private String renavan;
    private String chassis;
    private String chassis2;
    private String observacao;
    private String possuiRastrador;
    private String importado;
    private String blindado;
    private String sucata;
    private String proprioPortadoresDeficiencia;
    private String ipvapago;
    private String revisadoConcessionaria;
    private String garantiaFabrica;
    private String licenciado;
    private String vendidoAguardandoFaturamento;
    private String batido;
    private String entradaFacilitada;
    private String airBag;
    private String airBagMotorista;
    private String airBagDuplo;
    private String arCondicionado;
    private String arQuente;
    private String desembacadorTraseiro;
    private String cdPlayer;
    private String dvdPlayer;
    private String radio;
    private String tocaFitas;
    private String freiosABS;
    private String rodasLigaLeve;
    private String travaEletrica;
    private String vidrosEletricos;
    private String alarme;
    private String bancoCouro;
    private String direcaoHidraulica;
    private String limpadorTraseiro;
    private String tetoSolar;
    private String aberturaInternaPortaMalas;
    private String airbagCortina;
    private String airbagPassageiro;
    private String alarmeLuzesAcesas;
    private String bancoMotoristaAjusteAltura;
    private String bancoTraseiroRetratil;
    private String bancosDianteirosAquecimento;
    private String bancosEletricos;
    private String bluetooth;
    private String breakLight;
    private String capotaMaritima;
    private String carregadorCD;
    private String cartaoSD;
    private String cdPlayerMP3;
    private String computadorBordo;
    private String controleEstabilidade;
    private String volanteRegulagemAltura;
    private String vidrosVerdes;
    private String travaEletricaCentral;
    private String tracaoQuatroPorQuatro;
    private String controleSomVolante;
    private String controleTracao;
    private String direcaoEletrica;
    private String disqueteira;
    private String distribuicaoEletronicaFrenagem;
    private String encostoCabecaTraseiro;
    private String entradaAuxiliar;
    private String entradaUSB;
    private String faroisRegulagemInterna;
    private String faroisNeblinaDianteiros;
    private String faroisNeblinaTraseiros;
    private String farolNeblina;
    private String farolXenonio;
    private String imobilizadorMotor;
    private String gps;
    private String paraChoquesCorVeiculo;
    private String pilotoAutomatico;
    private String portaCopos;
    private String protetorCacamba;
    private String quebraMato;
    private String retrovisorFotocromico;
    private String radioTocaFitas;
    private String retrovisoresEletricos;
    private String santoAntonio;
    private String sensorChuva;
    private String sensorEstacionamento;
    private String sensorLuz;
    private String suporteEstepe;
    private List<Foto> fotos;
    private String emDestaque;

    // Getters and setters for all fields
    // (Adicione aqui os métodos getters e setters para cada campo)
}
